yahoo_columns <- c(
  # Player identification
  yahoo_id = "id", 
  player = "Player",
  team = "Team", 
  position = "Pos",
  
  # Offense
  passAtt = "Passing Att", 
  passComp = "Passing Comp", 
  passInc = "Passing Inc",
  passYds = "Passing Yds", 
  passTds = "Passing TD", 
  passInt = "Passing Int",
  sacks = "Passing Sack", 
  pass40Yds = "Passing 40 Yd Cmp", 
  pass40Tds = "Passing 40 Yd TD", 
  rushAtt = "Rushing Att", 
  rushYds = "Rushing Yds", 
  rushTds = "Rushing TD", 
  rush1st = "Rushing 1st Downs", 
  rush40Yds = "Rushing 40 Yd Att", 
  rush40Tds = "Rushing 40 YdTD", 
  targets = "Receiving Tgt", 
  rec = "Receiving Rec",
  recYds = "Receiving Yds", 
  recTds = "Receiving TD", 
  rec1st = "Receiving 1st Downs",
  rec40Yds = "Receiving 40 Yd Rec", 
  rec40Tds = "Receiving 40 Yd TD", 
  retYds = "Return Yds",
  retTds = "Return TD", 
  twoPts = "Misc 2PT", 
  allFumbles = "Fumbles Tot", 
  fumbles= "Fumbles Lost",
  
  # Kickers
  fg0019 = "Field Goals Made 0-19", 
  fg2029 = "Field Goals Made 20-29", 
  fg3039 = "Field Goals Made 30-39", 
  fg4049 = "Field Goals Made 40-49", 
  fg50= "Field Goals Made 50", 
  fgMiss0019 = "Field Goals Missed 0-19", 
  fgMiss2029 = "Field Goals Missed 20-29", 
  fgMiss3039 = "Field Goals Missed 30-39",
  fgMiss4049 = "Field Goals Missed 40-49", 
  fgMiss50 = "Field Goals Missed 50", 
  xp = "PAT Made", 
  xpMiss ="PAT Miss",
  
  # Defenses/Special Teams
  dstPtsAllow = "Pts vs.", 
  dstSacks = "Tackles Sack",
  dstSafety = "Tackles Safe",
  dstTFL = "Tackles TFL", 
  dstInt = "Turnovers Int", 
  dstFumRec = "Turnovers Fum Rec", 
  dstTD = "TD TD", 
  dstBlk = "Miscellaneous Blk Kick",
  dst4down = "Miscellaneous 4 Dwn Stops",
  dstYdsAllow = "Miscellaneous Yds Allow",
  dst3Out = "Miscellaneous 3 And Outs",
  dstReturnYds = "Return Yds", 
  dstReturnTds = "Return TD",
  
  # IDP
  idpRetYds = "Return Yds", 
  idpRetTds = "Return TD",
  idpSolo = "Tackles Tack Solo",
  idpAst = "Tackles Tack Ast",
  idpTFL = "Tackles TFL", 
  idpSack = "Tackles Sack",
  idpSafety = "Tackles Safe",
  idpPD = "Misc Pass Def",
  idpBlk = "Misc Blk Kick", 
  idpInt = "Turnovers Int", 
  idpFumForce = "Turnovers Fum Force",
  idpFumRec = "Turnovers Fum Rec",
  idpTORetYds = "Turnovers Ret Yds",
  idpTD = "TD TD"
)
